# File generated by az2tf see https://github.com/andyt530/az2tf
resource "azurerm_app_service" "disp-rg-commitments__tcfp-ws-commitmentser" {
  name                = "dis-prod-ws-commitments-west"
  location            = "West US"
  resource_group_name = "dis-prod-rg-commitments"
  app_service_plan_id = "/subscriptions/dc3c9354-6ca9-41a5-9559-479fbccf3217/resourceGroups/dis-prod-shared-resources-west/providers/Microsoft.Web/serverFarms/dis-prod-appsrv-plan-west"
}
