# File generated by az2tf see https://github.com/andyt530/az2tf
resource "azurerm_app_service" "ws-rac" {
  name                = "dis-prod-ws-rac"
  location            = "East US"
  resource_group_name = "dis-prod-rg-rac"
  app_service_plan_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/dis-prod-shared-resources-east/providers/Microsoft.Web/serverFarms/dis-prod-appsrv-plan-east" 
}

resource "azurerm_app_service_custom_hostname_binding" "ws-rac" {
  hostname            = "https://globalentry.21cf.com"
  app_service_name    = "${azurerm_app_service.ws-rac.name}"
  resource_group_name = "dis-prod-rg-rac"
}